slipstream/SlipStreamServerDeps

graphite/pom.xml, hsqldb/rpm/pom.xml, libcloud/rpm/pom.xml
Connected to slipstream/SlipStream#72.
=> fix python packaging for CentOS 7

hsqldb/rpm/pom.xml
Connected to slipstream/SlipStreamServer#365.
=> reduce dependency from jdk to jre

graphite/carbon-cache, graphite/pom.xml
Connected to SixSq/tasklist#390
=> graphite: Added a logrotate configuration for carbon-cache.

nginxconf/src/main/resources/conf/slipstream-extra/limits.block, nginxconf/src/main/resources/conf/slipstream-ssl.conf
Connected to SixSq/tasklist#494
=> Updated nginx limits

nginxconf/src/main/resources/conf/slipstream-extra/static-content.block
Connected to https://github.com/SixSq/tasklist/issues/642
=> Serve terms single page

nginxconf/src/main/resources/conf/slipstream-proxy.params, nginxconf/src/main/resources/conf/ssclj-proxy.params
=> ensure authn header is empty on proxied requests

nginxconf/src/main/resources/conf/slipstream-ssl.conf
instead of proxying with web server
connected to https://github.com/SixSq/tasklist/issues/689
=> Expose /api directly through nginx

hsqldb/rpm/pom.xml
=> make /etc/hsqldb.cfg config&noreplace in RPM

hsqldb/rpm/src/data/server.properties, hsqldb/rpm/src/etc/hsqldb.cfg, hsqldb/rpm/src/etc/hsqldb.service
=> remove dependency of ssclj on hsqldb

nginxconf/src/main/resources/conf/slipstream-proxy.params, nginxconf/src/main/resources/conf/ssclj-proxy.params
=> add header for requested SNI hostname

nginxconf/src/main/resources/conf/slipstream-proxy.params, nginxconf/src/main/resources/conf/ssclj-proxy.params
=> fix variable name for SNI hostname

nginxconf/src/main/resources/conf/slipstream-extra/limit-reports.block
=> increase maximum size of report put

pom.xml, riemann/jar/boot.properties, riemann/jar/build.boot, riemann/jar/pom.xml, riemann/jar/src/sixsq/slipstream/api/service_offer.clj, riemann/pom.xml, riemann/rpm/pom.xml, riemann/rpm/streams/nuvlabox-streams.clj
=> move riemann dependency to community

backup/pom.xml, es-repo/pom.xml, graphite/pom.xml, hsqldb/pom.xml, hsqldb/rpm/pom.xml, libcloud/pom.xml, libcloud/rpm/pom.xml, nginxconf/pom.xml, phantomjs/pom.xml, pom.xml, riemann/rpm/pom.xml, ssuseradd/pom.xml
Connected to SixSq/tasklist#982
=> unify community/enterprise rpms

riemann/rpm/pom.xml
=> give jar a relevant name

riemann/jar/build.boot, riemann/jar/pom.xml, riemann/rpm/pom.xml
Connected to SixSq/tasklist#983
=> push on env var

backup/src/es/nagios_check_slipstream_es_backup_timestamp, backup/src/es/slipstream-es-backup.conf, backup/src/es/slipstream-es-backup.sh, backup/src/slipstream-backup.conf
=> Issue #56 es backup missing

riemann/jar/pom.xml, riemann/rpm/pom.xml
Connected to slipstream/SlipStreamServer#916
=> dependency cleanup

es-repo/src/main/config/elasticsearch.repo
=> Issue #927 elasticsearch 5x

nginxconf/src/main/resources/conf/slipstream-extra/webui.block, nginxconf/src/main/resources/conf/slipstream.params
Connected to slipstream/SlipStreamWebUI#1
=> serve webui from nginx

nginxconf/src/main/resources/conf/slipstream-extra/webui.block
Connected to slipstream/SlipStreamWebUI#1
=> fix webui location

graphite/collectd-graphite-ss.conf, graphite/pom.xml, graphite/storage-schemas_ss.conf
=> extra configuration for graphite and collectd

nginxconf/src/main/resources/conf/slipstream-extra/webui.block
=> ensure all webui addresses are sent to SPA

pom.xml
fix : build phantomjs rpm conditionaly
=> Related to #82

nginxconf/src/main/resources/conf/slipstream-extra/uibis.block, nginxconf/src/main/resources/conf/slipstream.params
Serve the uibis application to allow the old UI to pick up new pages. 
Connected to slipstream/SlipStreamUI#730.
=> serve uibis application just like webui application

nginxconf/src/main/resources/conf/slipstream-extra/authn.block, nginxconf/src/main/resources/conf/slipstream.params
Connected to slipstream/SlipStreamUI#730.
=> rename authn page cfg

backup/src/es/slipstream-es-backup.conf, backup/src/es/slipstream-es-backup.sh, backup/src/slipstream-backup.conf
=> update ES backup script
